//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Procbel.Apps.Model.Main
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppsMainContainer : DbContext
    {
        public AppsMainContainer()
            : base("name=AppsMainContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Site> Sites { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Supplier> Suppliers { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Image> Images { get; set; }
        public DbSet<FactTag> FactTags { get; set; }
        public DbSet<Asset> Assets { get; set; }
        public DbSet<DimDate> DimDates { get; set; }
        public DbSet<Location> Locations { get; set; }
        public DbSet<InfoTag> InfoTags { get; set; }
        public DbSet<ReaderTag> ReaderTags { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductCategory> ProductCategories { get; set; }
        public DbSet<productAssortment> productAssortments { get; set; }
        public DbSet<ProductBox> ProductBoxes { get; set; }
        public DbSet<EmployeeShifts> EmployeeShifts { get; set; }
        public DbSet<ReaderTagAntena> ReaderTagAntenas { get; set; }
        public DbSet<DimTime> DimTime { get; set; }
        public DbSet<TicketAttachment> TicketAttachments { get; set; }
        public DbSet<TicketComment> TicketComments { get; set; }
        public DbSet<TicketEventNotification> TicketEventNotifications { get; set; }
        public DbSet<Ticket> Tickets { get; set; }
        public DbSet<TicketTag> TicketTags { get; set; }
        public DbSet<Setting> Settings { get; set; }
        public DbSet<TicketType> TicketTypeSet { get; set; }
        public DbSet<TicketCategory> TicketCategorySet { get; set; }
        public DbSet<TicketStatus> TicketStatusSet { get; set; }
        public DbSet<Activity> Activity { get; set; }
        public DbSet<Company> Company { get; set; }
        public DbSet<Contact> Contact { get; set; }
        public DbSet<Opportunity> Opportunity { get; set; }
        public DbSet<SalesTrend> SalesTrend { get; set; }
        public DbSet<LocationType> LocationTypes { get; set; }
        public DbSet<LocationHierarchyLevel> LocationHierarchyLevels { get; set; }
        public DbSet<ProductCatalogStructure> ProductCatalogStructures { get; set; }
        public DbSet<ProductCatalog> ProductCatalogs { get; set; }
        public DbSet<Document> DocumentSet { get; set; }
        public DbSet<Code> Code { get; set; }
    }
}
