//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Procbel.Apps.Model.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Id { get; set; }
        public int SiteId { get; set; }
        public string Propiedad1 { get; set; }
        public Nullable<decimal> Credito { get; set; }
    
        public virtual Site Site { get; set; }
        public virtual Company Company { get; set; }
    }
}
