//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Procbel.Apps.Model.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimDate
    {
        public int Id { get; set; }
        public string FullDate { get; set; }
        public string DateName { get; set; }
        public string DateNameUS { get; set; }
        public string DateNameEU { get; set; }
        public string DayOfWeek { get; set; }
        public string DayOfWeekName { get; set; }
        public string DayOfWeekNameSpanish { get; set; }
        public string DayOfWeekNameChinese { get; set; }
        public string DayOfMonth { get; set; }
        public string DayOfYear { get; set; }
        public string WeekdayWeekend { get; set; }
        public string WeekOfYear { get; set; }
        public string MonthName { get; set; }
        public string MonthNameSpanish { get; set; }
        public string MonthNameChinese { get; set; }
        public string MonthOfYear { get; set; }
        public string IsLastDayOfMonth { get; set; }
        public string CalendarQuarter { get; set; }
        public string CalendarYear { get; set; }
        public string CalendarYearMonth { get; set; }
        public string CalendarYearQtr { get; set; }
        public string FiscalMonthOfYear { get; set; }
        public string FiscalQuarter { get; set; }
        public short FiscalYear { get; set; }
        public string FiscalYearMonth { get; set; }
        public string FiscalYearQtr { get; set; }
    }
}
