//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Procbel.Apps.Model.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int Id { get; set; }
        public string DocumentPath { get; set; }
        public byte[] Content { get; set; }
        public string Extension { get; set; }
        public string MimeType { get; set; }
        public string Name { get; set; }
        public double Size { get; set; }
    }
}
