//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Procbel.Apps.Model.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.EmployeeShifts = new HashSet<EmployeeShifts>();
            this.Activities = new HashSet<Activity>();
        }
    
        public int Id { get; set; }
        public int SiteId { get; set; }
        public string IdentificationTagId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Position { get; set; }
        public string Phone { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ImageId { get; set; }
    
        public virtual Site Site { get; set; }
        public virtual ICollection<EmployeeShifts> EmployeeShifts { get; set; }
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual Image Image { get; set; }
    }
}
