//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Procbel.Apps.Model.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactTag
    {
        public int Id { get; set; }
        public int SiteId { get; set; }
        public int DimDateId { get; set; }
        public int DimTimeId { get; set; }
        public string TagId { get; set; }
        public int LocationId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> ProductCategoryId { get; set; }
        public Nullable<int> productAssortmentId { get; set; }
        public Nullable<int> ProductBoxId { get; set; }
    
        public virtual Site Site { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual productAssortment productAssortment { get; set; }
        public virtual ProductBox ProductBox { get; set; }
    }
}
