//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Procbel.Apps.Model.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public Image()
        {
            this.Site = new HashSet<Site>();
            this.Contacts = new HashSet<Contact>();
            this.Products = new HashSet<Product>();
            this.Employees = new HashSet<Employee>();
            this.Locations = new HashSet<Location>();
            this.Companies = new HashSet<Company>();
        }
    
        public int Id { get; set; }
        public string ImagePath { get; set; }
        public byte[] Content { get; set; }
        public string Extension { get; set; }
        public string MimeType { get; set; }
        public string Name { get; set; }
        public double Size { get; set; }
    
        public virtual ICollection<Site> Site { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<Company> Companies { get; set; }
    }
}
