//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Procbel.Apps.Model.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.InfoTags = new HashSet<InfoTag>();
            this.LocationTypes = new HashSet<LocationType>();
        }
    
        public int Id { get; set; }
        public int SiteId { get; set; }
        public string Name { get; set; }
        public System.Data.Spatial.DbGeography SpaceCenter { get; set; }
        public Nullable<int> parentId { get; set; }
        public short hierarchyLevel { get; set; }
        public string fullPath { get; set; }
        public Nullable<int> ImageId { get; set; }
        public System.Data.Spatial.DbGeometry MapPath { get; set; }
        public int HierarchyLevelId { get; set; }
        public string ShapeFileUri { get; set; }
        public string ShapeFileDataUri { get; set; }
    
        public virtual Site Site { get; set; }
        public virtual ICollection<InfoTag> InfoTags { get; set; }
        public virtual Location LocationParent { get; set; }
        public virtual Image Image { get; set; }
        public virtual ICollection<LocationType> LocationTypes { get; set; }
        public virtual LocationHierarchyLevel LocationHierarchyLevel { get; set; }
    }
}
