//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Procbel.Apps.Model.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opportunity
    {
        public Opportunity()
        {
            this.Activity = new HashSet<Activity>();
        }
    
        public int OpportunityID { get; set; }
        public int SiteId { get; set; }
        public string Description { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Lead { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Stage { get; set; }
        public Nullable<int> SuccessProbability { get; set; }
        public string WonLostReason { get; set; }
        public Nullable<int> DiscountPercent { get; set; }
        public string DiscountReason { get; set; }
        public Nullable<System.DateTime> EstimationCloseDate { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public int DimDateCreatedId { get; set; }
        public int DimTimeCreatedId { get; set; }
    
        public virtual ICollection<Activity> Activity { get; set; }
        public virtual Company Company { get; set; }
        public virtual Product Product { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual Site Site { get; set; }
    }
}
