//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Procbel.Apps.Model.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductBox
    {
        public ProductBox()
        {
            this.FactTags = new HashSet<FactTag>();
        }
    
        public int Id { get; set; }
        public int SiteId { get; set; }
        public string Name { get; set; }
        public string NameEnglish { get; set; }
        public string NameChinese { get; set; }
        public double NetWeight { get; set; }
        public ProductType ProductType { get; set; }
    
        public virtual Site Site { get; set; }
        public virtual ICollection<FactTag> FactTags { get; set; }
    }
}
