//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Procbel.Apps.Model.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Opportunities = new HashSet<Opportunity>();
        }
    
        public int Id { get; set; }
        public int SiteId { get; set; }
        public string ProductNumber { get; set; }
        public string Name { get; set; }
        public string EnglishName { get; set; }
        public string FrenchName { get; set; }
        public string ChineseName { get; set; }
        public Nullable<int> ProductCategoryId { get; set; }
        public ProductType ProductType { get; set; }
        public string Features { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public int ImageId { get; set; }
        public string Description { get; set; }
        public string EnglishDescription { get; set; }
        public string FrenchDescription { get; set; }
        public string ChineseDescription { get; set; }
        public string ArabicDescription { get; set; }
        public string HebrewDescription { get; set; }
        public string ThaiDescription { get; set; }
        public string GermanDescription { get; set; }
        public string JapaneseDescription { get; set; }
        public string TurkishDescription { get; set; }
    
        public virtual Site Site { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual Image Image { get; set; }
        public virtual ICollection<Opportunity> Opportunities { get; set; }
    }
}
