//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Procbel.Apps.Model.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategory
    {
        public ProductCategory()
        {
            this.Products = new HashSet<Product>();
            this.FactTags = new HashSet<FactTag>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string NameEnglish { get; set; }
        public string NameChinese { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<FactTag> FactTags { get; set; }
    }
}
