//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Procbel.Apps.Model.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReaderTag
    {
        public ReaderTag()
        {
            this.CanWrite = false;
            this.OnDemand = false;
            this.ReaderTagAntenas = new HashSet<ReaderTagAntena>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Model { get; set; }
        public string IP { get; set; }
        public string Port { get; set; }
        public string Com { get; set; }
        public bool CanWrite { get; set; }
        public bool OnDemand { get; set; }
    
        public virtual ICollection<ReaderTagAntena> ReaderTagAntenas { get; set; }
    }
}
