//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Procbel.Apps.Model.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        public Site()
        {
            this.Employees = new HashSet<Employee>();
            this.FactTags = new HashSet<FactTag>();
            this.Customers = new HashSet<Customer>();
            this.Suppliers = new HashSet<Supplier>();
            this.Assets = new HashSet<Asset>();
            this.Locations = new HashSet<Location>();
            this.Products = new HashSet<Product>();
            this.ProductBoxes = new HashSet<ProductBox>();
            this.Ticket = new HashSet<Ticket>();
            this.Settings = new HashSet<Setting>();
            this.Companies = new HashSet<Company>();
            this.LocationTypes = new HashSet<LocationType>();
            this.Opportunities = new HashSet<Opportunity>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ImageId { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<FactTag> FactTags { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Supplier> Suppliers { get; set; }
        public virtual ICollection<Asset> Assets { get; set; }
        public virtual Image Image { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<ProductBox> ProductBoxes { get; set; }
        public virtual ICollection<Ticket> Ticket { get; set; }
        public virtual ICollection<Setting> Settings { get; set; }
        public virtual ICollection<Company> Companies { get; set; }
        public virtual ICollection<LocationType> LocationTypes { get; set; }
        public virtual ICollection<Opportunity> Opportunities { get; set; }
    }
}
