//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Procbel.Apps.Model.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketEventNotification
    {
        public int TicketId { get; set; }
        public int CommentId { get; set; }
        public string NotifyUser { get; set; }
        public string NotifyUserDisplayName { get; set; }
        public string NotifyEmail { get; set; }
        public string NotifyUserReason { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int DeliveryAttempts { get; set; }
        public Nullable<System.DateTime> LastDeliveryAttemptDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> NextDeliveryAttemptDate { get; set; }
        public string EventGeneratedByUser { get; set; }
    
        public virtual TicketComment TicketComment { get; set; }
    }
}
