//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Procbel.Apps.Model.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketComment
    {
        public TicketComment()
        {
            this.TicketEventNotifications = new HashSet<TicketEventNotification>();
        }
    
        public int TicketId { get; set; }
        public int CommentId { get; set; }
        public string CommentEvent { get; set; }
        public string Comment { get; set; }
        public bool IsHtml { get; set; }
        public string CommentedBy { get; set; }
        public System.DateTime CommentedDate { get; set; }
        public System.Guid Version { get; set; }
    
        public virtual Ticket Ticket { get; set; }
        public virtual ICollection<TicketEventNotification> TicketEventNotifications { get; set; }
    }
}
