//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Procbel.Apps.Model.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketAttachment
    {
        public Nullable<int> TicketId { get; set; }
        public int FileId { get; set; }
        public string FileName { get; set; }
        public int FileSize { get; set; }
        public string FileType { get; set; }
        public string UploadedBy { get; set; }
        public System.DateTime UploadedDate { get; set; }
        public byte[] FileContents { get; set; }
        public string FileDescription { get; set; }
        public bool IsPending { get; set; }
        public string FileUrl { get; set; }
    
        public virtual Ticket Ticket { get; set; }
    }
}
