//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Procbel.Apps.Model.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public Ticket()
        {
            this.TicketAttachments = new HashSet<TicketAttachment>();
            this.TicketComments = new HashSet<TicketComment>();
            this.TicketTags = new HashSet<TicketTag>();
        }
    
        public int TicketId { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public bool IsHtml { get; set; }
        public string TagList { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Owner { get; set; }
        public string AssignedTo { get; set; }
        public System.DateTime CurrentStatusDate { get; set; }
        public string CurrentStatusSetBy { get; set; }
        public string LastUpdateBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string Priority { get; set; }
        public bool AffectsCustomer { get; set; }
        public bool PublishedToKb { get; set; }
        public System.Guid Version { get; set; }
        public int DimCreatedDateId { get; set; }
        public int DimCreatedTimeId { get; set; }
        public int DimCurrentStatusDateId { get; set; }
        public int DimCurrentStatusTimeId { get; set; }
        public int SiteId { get; set; }
        public int TicketCategoryTicketCategoryId { get; set; }
        public int TicketTypeTicketTypeId { get; set; }
        public int TicketStatusTicketStatusId { get; set; }
    
        public virtual ICollection<TicketAttachment> TicketAttachments { get; set; }
        public virtual ICollection<TicketComment> TicketComments { get; set; }
        public virtual Site Site { get; set; }
        public virtual TicketCategory TicketCategory { get; set; }
        public virtual TicketType TicketType { get; set; }
        public virtual TicketStatus TicketStatus { get; set; }
        public virtual ICollection<TicketTag> TicketTags { get; set; }
    }
}
