//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Procbel.Apps.Model.AdventureWorksDW2008R2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimProductCategory
    {
        public DimProductCategory()
        {
            this.DimProductSubcategory = new HashSet<DimProductSubcategory>();
        }
    
        public int ProductCategoryKey { get; set; }
        public Nullable<int> ProductCategoryAlternateKey { get; set; }
        public string EnglishProductCategoryName { get; set; }
        public string SpanishProductCategoryName { get; set; }
        public string FrenchProductCategoryName { get; set; }
    
        public virtual ICollection<DimProductSubcategory> DimProductSubcategory { get; set; }
    }
}
