//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Procbel.Apps.Model.CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int ActivityID { get; set; }
        public Nullable<int> Type { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Notes { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> OpportunityID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Opportunity Opportunity { get; set; }
    }
}
