//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Procbel.Apps.Model.CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Contact = new HashSet<Contact>();
            this.Opportunity = new HashSet<Opportunity>();
            this.SalesTrend = new HashSet<SalesTrend>();
        }
    
        public int CompanyID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Postcode { get; set; }
        public string Website { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> Revenue { get; set; }
        public string NASDAQ { get; set; }
        public string Industry { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ImageID { get; set; }
    
        public virtual Image Image { get; set; }
        public virtual ICollection<Contact> Contact { get; set; }
        public virtual ICollection<Opportunity> Opportunity { get; set; }
        public virtual ICollection<SalesTrend> SalesTrend { get; set; }
    }
}
